WebApp/WebApp/Controllers/HomeController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.Services;
using System.Web.UI.WebControls;
using WebApp.Models;

namespace WebApp.Controllers
{
    [System.Web.Http.Authorize]
    public class HomeController : Controller
    {

        public ActionResult Index()
        {

            ViewBag.Title = "FINE";
            if (Response.Cookies["Filter"].Value == null)
            {
                Response.Cookies["Filter"].Value = String.Empty;
                Response.Cookies["Filter"].Value = String.Empty;
            }
            if (WebApiApplication.LOGED_IN)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult SignOut()
        {
            WebApiApplication.LOGED_IN = false;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Terms()
        {
            return View("Terms");
        }

        public ActionResult FilterRestaurants(string filter)
        {
            WebApiApplication.filteredRestaurants = WebApiApplication.restaurants.Where(r => r.RestaurantName.ToLower().Contains(filter.ToLower())).ToList();
            Response.Cookies.Add(new HttpCookie("Filter", filter));
            Response.Cookies["Filter"].Expires = DateTime.Now.AddMinutes(5);
            return View("Index");
        }

        public ActionResult RestaurantDetails(string name)
        {

            if (WebApiApplication.LOGED_IN && name != null)
            {
                List<int> VIDints = new List<int>();
                HelperModel helperModel = new HelperModel()
                {
                    RestaurantModel = WebApiApplication.restaurants.Where(r => r.RestaurantName == name).FirstOrDefault(),
                    VIDs = VIDints
                };
                string VIDs = Session["VIDs"] as String;
                if (VIDs != String.Empty)
                {
                    List<String> VIDstrings = VIDs.Split(',').ToList();
                    VIDstrings.ForEach(v => VIDints.Add(int.Parse(v)));
                    helperModel.VIDs = VIDints;
                    return View("RestaurantDetails", helperModel);

                }

                return View("RestaurantDetails", helperModel);

            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult UpdateGrade(string RestaurantName, int rVID)
        {
            string currentUser = Session["username"] as String;
            RestaurantModel model = WebApiApplication.restaurants.Where(r => r.RestaurantName == RestaurantName).FirstOrDefault();


            //StringBuilder stringBuilder = new StringBuilder();
            //int postfix = 1;
            //    //umjesto 4 napisi listu hrane iz restorana
            //    for (int i = 0; i < 4; i++)
            //    {
            //        for (int j = 0; j < 5; j++)
            //        {
            //            stringBuilder.Append(Request.Form["cbf" + postfix.ToString()]);
            //            if (!(i == 3 && j == 4))
            //            {
            //                stringBuilder.Append(",");
            //            }
            //            postfix++;
            //        }
            //    }
            bool rest = SetRestaurantGradeSpread("cbr", model);
            List<GradeSpread> FGradeSpread = GetGradeSpread("cbf", model);
            List<GradeSpread> WGradeSpread = GetGradeSpread("cbw", model);


            List<string> vidslist = new List<string>();
            //if (rVID != -1)
            //{
            //    vidslist.Add(rVID.ToString());

            //}
            int Fcounter = 0;
            if (FGradeSpread != null)
            {

                foreach (var food in FGradeSpread)
                {
                    model.Food[Fcounter].Grade.One += food.One;
                    model.Food[Fcounter].Grade.Two += food.Two;
                    model.Food[Fcounter].Grade.Three += food.Three;
                    model.Food[Fcounter].Grade.Four += food.Four;
                    model.Food[Fcounter].Grade.Five += food.Five;
                    if (!(food.Five == 0 && food.Four == 0 && food.Three == 0 && food.Two == 0 && food.One == 0))
                    {
                        vidslist.Add(model.Food[Fcounter].VID.ToString());
                    }
                    Fcounter++;
                }
            }

            int Wcounter = 0;
            if (WGradeSpread != null)
            {
                foreach (var wine in WGradeSpread)
                {
                    model.Wine[Wcounter].Grade.One += wine.One;
                    model.Wine[Wcounter].Grade.Two += wine.Two;
                    model.Wine[Wcounter].Grade.Three += wine.Three;
                    model.Wine[Wcounter].Grade.Four += wine.Four;
                    model.Wine[Wcounter].Grade.Five += wine.Five;
                    if (!(wine.Five == 0 && wine.Four == 0 && wine.Three == 0 && wine.Two == 0 && wine.One == 0))
                    {
                        vidslist.Add(model.Wine[Wcounter].VID.ToString());

                    }
                    Wcounter++;
                }
            }
            string finalVIDS = rest== true ? rVID.ToString() + "," : String.Empty;
            //vidslist.ForEach(v=>finalVIDS.Join(",",v.ToString()));
            foreach (var v in vidslist)
            {
                //if (finalVIDS == String.Empty)
                //{
                //    finalVIDS += v.ToString() + ",";

                //}
                //else
                //{
                //    finalVIDS += v.ToString() + ",";
                //}
                finalVIDS += v.ToString() + ",";


            }
            if (Session["VIDs"] as String != String.Empty)
            {
                finalVIDS = Session["VIDs"] as String + "," + finalVIDS;
            }
            if (finalVIDS.Length>0)
            {
                finalVIDS = finalVIDS.Remove(finalVIDS.Length - 1);
            }
            Session["VIDs"] = finalVIDS;
            //string test = Session["VIDs"] as String;

            RestaurantUserCombo restaurantUserCombo = new RestaurantUserCombo() { RestaurantModel = model, WebUser = new WebUser() { Username = currentUser, VIDs = finalVIDS } };

            //string xmlPath = ControllerContext.HttpContext.Server.MapPath("~/example.xml");

            RestaurantsUserCombo restaurantsUserCombo =  WebApiApplication.BackendPostWithReturn<RestaurantUserCombo, RestaurantsUserCombo>(restaurantUserCombo, WebApiApplication.URL_GRADE_UPDATE_PATH);
            Session["username"] = restaurantsUserCombo.WebUser.Username;
            WebApiApplication.restaurants = restaurantsUserCombo.RestaurantModels;
            WebApiApplication.filteredRestaurants = WebApiApplication.restaurants;

            HelperModel helperModel = WebApiApplication.currentHelperModel;
            helperModel.RestaurantModel = model;
            if (finalVIDS != String.Empty)
            {
                List<String> VIDstrings = finalVIDS.Split(',').ToList();
                VIDstrings.ForEach(v => helperModel.VIDs.Add(int.Parse(v)));

            }

            return View("RestaurantDetails", helperModel);
        }

        private bool SetRestaurantGradeSpread(string clue, RestaurantModel model)
        {

            String grade = Request.Form[clue];
            //List<string> grades = request.ToString().Split(',').ToList();

            //foreach (var grade in grades)
            //{
            switch (grade)
            {
                case "One":
                    model.Grade.One += 1;
                    return true;
                case "Two":
                    model.Grade.Two += 1;
                    return true;

                case "Three":
                    model.Grade.Three += 1;
                    return true;

                case "Four":
                    model.Grade.Four += 1;
                    return true;

                case "Five":
                    model.Grade.Five += 1;
                    return true;

                default:
                    return false;

            }
            //}
        }

        private List<GradeSpread> GetGradeSpread(string clue, RestaurantModel model)
        {

            List<GradeSpread> finalGradeSpreads = new List<GradeSpread>();

            StringBuilder stringBuilder = new StringBuilder();

            int prefix = 1;
            if (clue == "cbf")
            {
                if (model.Food.Count == 0)
                {
                    return null;
                }
                //umjesto 4 napisi listu hrane iz restorana
                //for (int i = 0; i < 4; i++)
                //{
                //    for (int j = 0; j < 5; j++)
                //    {
                //        stringBuilder.Append(Request.Form[clue + i.ToString() + postfix.ToString()]);
                //        if (!(i == 3 && j == 4))
                //        {
                //            stringBuilder.Append(",");
                //        }
                //        postfix++;
                //    }
                //}
                for (int i = 0; i < model.Food.Count; i++)
                {
                    stringBuilder.Append(Request.Form[clue + prefix.ToString()]);
                    if (!(i == model.Food.Count - 1))
                    {
                        stringBuilder.Append(",");
                    }
                    prefix++;

                }
            }
            else
            {
                //umjesto 4 napisi listu vina iz restorana
                //for (int i = 0; i < 4; i++)
                //{

WebApp/WebApp/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection.Emit;
using System.Runtime.Serialization;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class RegistrationController : Controller
    {
        //// GET: Registration
        //public ActionResult Index()
        //{

        //    return View();
        //}

        [HttpPost]
        public ActionResult Index(string url)
        {
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Register(string userName,string email,string pass,string pswRepeat)
        {

            WebUser user = new WebUser();
            user.Username = userName;
            user.Email = email;
            user.Pass = pass;

            if (!email.Contains("@") || !email.Contains("."))
            {
                ViewBag.Info = "E-Mail is not in the correct format";
                //Response.Cookies["lblInfo"].Value = "E-Mail is not in the correct format";
                //Response.Cookies["lblInfo"].Expires = DateTime.Now.AddMinutes(5);
                //return RedirectToAction("Registration", "Login");
            }

            //Provjera
            WebApiApplication.BackendPost<WebUser>(user, WebApiApplication.URL_REGISTRATION_PATH);

            return RedirectToAction("Index", "Login");
        }
    }
}

WebApp/WebApp/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">
    @*<link href="~/Content/RestaurantOverview.css" rel="stylesheet" />*@
    @Styles.Render("~/Content/css")
    <title>FINE</title>
</head>
<body class="RestaurantBG">
    <div style="margin-bottom:40px; padding-bottom:30px;">
        @using (Html.BeginForm("FilterRestaurants", "Home", FormMethod.Post, new
        {
            id = "filterForm"
        }))
        {
            <input id="autoCompInput" placeholder='@WebApp.Resources.DefaultLanguage.FilterRestaurants' value="@Response.Cookies["Filter"].Value.ToString()" type="text" name="filter" class="navbar-brand form-control" style="position:relative; margin-left:39%;" />
        }
        <script>
            $(document).ready(function () {
                $("#autoCompInput").bind("keypress", {}, keypressInBox);

                function keypressInBox(e) {
                    var code = (e.keyCode ? e.keyCode : e.which);
                    if (code == 13) { //Enter keycode
                        e.preventDefault();

                        $("filterForm").submit();
                    }
                };
            });
        </script>
    </div>


    @*<br />
    <br />
    <br />*@
    @foreach (WebApp.Models.RestaurantModel r in WebApiApplication.filteredRestaurants)
    {
        <div id="divLogin" class="col-md-4">
            <a href="@Url.Action("RestaurantDetails", "Home", new { name = r.RestaurantName })" class="RestaurantCard">
                <div id="slide" class="jumbotron" style="background-color: #3e3e3eba;">
                    <div class="row" style="text-align:center;">
                        @*style="justify-content:center;text-align:center;align-content:center;"*@
                        <label id="lblTitle" class="RestaurantTitle">@r.RestaurantName</label>
                        @*@Html.Label(r.RestaurantName, htmlAttributes: new { @class = "text-center" })*@
                        <img src="@r.Image" alt="" asp-append-version="true" class="RestaurantImage" />
                        <br />
                        <br />
                        <br />
                        @Html.Label(r.RestaurantDetails, htmlAttributes: new { @class = "text-center", style = "font-family:'Poppins',sans-serif; color:#ffffff99;" })

                        @{decimal nbrReviews = r.Grade.Five + r.Grade.Four + r.Grade.Three + r.Grade.Two + r.Grade.One;}
                        @if (nbrReviews == 0)
                        {
                            nbrReviews = 1;
                        }
                        <br />
                        <br />

                        @{decimal sum = 5 * r.Grade.Five + 4 * r.Grade.Four + 3 * r.Grade.Three + 2 * r.Grade.Two + r.Grade.One;}
                        @{decimal average = Math.Round(sum / nbrReviews, 2);}
                        @{decimal intPart = Math.Truncate(average); decimal DecimalPart = (average - intPart) * 100; int counter = 5;}
                        @Html.Label("Korisničko zadovoljstov: ", htmlAttributes: new { @class = " text-center", style = "font-family:'Poppins',sans-serif; color:#ffffff99;" })
                        @Html.Label(Math.Truncate(average).ToString() +","+ Math.Truncate(DecimalPart).ToString()+ "/5", htmlAttributes: new { @class = " text-center", style = "font-family:'Poppins',sans-serif; color:#ffffff99;" })
                        
                        <br />
                        @while (counter > 0)
                        {
                            while (Math.Truncate(intPart) > 0)
                            {
                                <i class="fa fa-star MyStar" style="text-shadow: 0 2px 5px rgba(0,0,0,.5);"></i>
                                intPart--;
                                counter--;
                            }

                            if (DecimalPart >= 50)
                            {
                                <i class="fa fa-star-half-full MyStar" style="text-shadow: 0 2px 5px rgba(0,0,0,.5);"></i>
                                DecimalPart = 0;

                            }
                            else
                            {
                                if (counter != 0)
                                {
                                    <i class="fa fa-star-o MyStar" style="text-shadow: 0 2px 5px rgba(0,0,0,.5);"></i>
                                }
                            }
                            counter--;
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</body>
</html>

WebApp/WebApp/Views/Home/Terms.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Terms</title>
</head>
<body>
    <div>
        @Html.ActionLink("WE HAVE NO TERMS!!! Good luck! :)", "Index", "Registration",new { @style="text-decoration: none;text-align:center;"})
      
    </div>
</body>
</html>